local MenuOri = 0
_MenuPool = NativeUI.CreatePool()
EUPMenu = NativeUI.CreateMenu('EUP Menu', "Main Menu", 0, MenuOri)


RegisterCommand("eup", function() 
	if not menuOpen then
    local ped = PlayerPedId()
    if GetEntityModel(ped) == GetHashKey("mp_m_freemode_01") then
       	 	EUPMenu()
			EUPMenu:Visible(true)
    	elseif GetEntityModel(ped) == GetHashKey("mp_f_freemode_01") then
        	EUPMenu()
			EUPMenu:Visible(true)
    	else
        	ShowInfo("You need to use an MP ped with EUP")
    end	
	else
		_MenuPool:CloseAllMenus()
	end
end)

function ShowInfo(text)
  SetTextComponentFormat("STRING")
  AddTextComponentString(text)
  DisplayHelpTextFromStringLabel(0, 0, 0, -1)
end

function EUPMenu()	
	_MenuPool:Remove()
	_MenuPool = NativeUI.CreatePool()
	EUPMenu = NativeUI.CreateMenu('EUP Menu', "Main Menu", 0, MenuOri)
	_MenuPool:Add(EUPMenu)
	EUPMenu:SetMenuWidthOffset(20)

	local EUPPedPresets = _MenuPool:AddSubMenu(EUPMenu, 'Ped Presets', 'Ped Presets.', true)
	EUPPedPresets:SetMenuWidthOffset(20)
		local EUPPedPresetsLSPD = _MenuPool:AddSubMenu(EUPPedPresets, 'Los Santos Police Department', '', true)
		EUPPedPresetsLSPD:SetMenuWidthOffset(20)

			local EUPPedPresetsLSPDMetro = _MenuPool:AddSubMenu(EUPPedPresetsLSPD, 'Metro', '', true)
			EUPPedPresetsLSPDMetro:SetMenuWidthOffset(20)

			local EUPPedPresetsLSPDMetroSupervisor = _MenuPool:AddSubMenu(EUPPedPresetsLSPDMetro, 'Supervisor', '', true)
			EUPPedPresetsLSPDMetro:SetMenuWidthOffset(20)

			LSPDPedPresetsClassA = NativeUI.CreateItem('Class A', '')
			LSPDPedPresetsClassA:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassB = NativeUI.CreateItem('ClassB', '')
			LSPDPedPresetsClassB:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassC = NativeUI.CreateItem('ClassC', '')
			LSPDPedPresetsClassC:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassWinterCoat = NativeUI.CreateItem('Winter Coat', '')
			LSPDPedPresetsClassWinterCoat:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassTshirt = NativeUI.CreateItem('T-Shirt', '')
			LSPDPedPresetsClassTshirt:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassLongSleeveShirt = NativeUI.CreateItem('Long Sleeve Shirt', '')
			LSPDPedPresetsClassLongSleeveShirt:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassWindBreaker = NativeUI.CreateItem('Windbreaker', '')
			LSPDPedPresetsClassWindBreaker:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsClassPolo = NativeUI.CreateItem('Polo', '')
			LSPDPedPresetsClassPolo:SetLeftBadge(BadgeStyle.Clothes)
			
			EUPPedPresetsLSPDMetro:AddItem(LSPDPedPresetsClassA)
			EUPPedPresetsLSPDMetro:AddItem(LSPDPedPresetsClassB)
			EUPPedPresetsLSPDMetro:AddItem(LSPDPedPresetsClassC)
			EUPPedPresetsLSPDMetro:AddItem(LSPDPedPresetsClassWinterCoat)
			EUPPedPresetsLSPDMetroSupervisor:AddItem(LSPDPedPresetsClassTshirt)
			EUPPedPresetsLSPDMetroSupervisor:AddItem(LSPDPedPresetsClassLongSleeveShirt)
			EUPPedPresetsLSPDMetroSupervisor:AddItem(LSPDPedPresetsClassWindBreaker)
			EUPPedPresetsLSPDMetroSupervisor:AddItem(LSPDPedPresetsClassPolo)

			LSPDPedPresetsClassA.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 60, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 200, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end
			
			LSPDPedPresetsClassB.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 60, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 45, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 102, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsClassC.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 19, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 60, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 45, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 101, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end
			
			LSPDPedPresetsClassWinterCoat.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 60, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 45, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 81, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsClassTshirt.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 19, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 52, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 108, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsClassLongSleeveShirt.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 33, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 67, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 92, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsClassWindBreaker.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 152, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 54, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 1, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 45, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 3, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsClassPolo.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 41, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 109, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 2, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			local EUPPedPresetsLSPDsvpd = _MenuPool:AddSubMenu(EUPPedPresetsLSPD, 'Senora Valley', '', true)
			EUPPedPresetsLSPDsvpd:SetMenuWidthOffset(20)

			local EUPPedPresetsLSPDsvpdSupervisor = _MenuPool:AddSubMenu(EUPPedPresetsLSPDsvpd, 'Supervisor', '', true)
			EUPPedPresetsLSPDsvpd:SetMenuWidthOffset(20)

			LSPDPedPresetsSVPDClassA = NativeUI.CreateItem('Class A', '')
			LSPDPedPresetsSVPDClassA:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDClassB = NativeUI.CreateItem('Class B', '')
			LSPDPedPresetsSVPDClassB:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDClassC = NativeUI.CreateItem('Class C', '')
			LSPDPedPresetsSVPDClassC:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDTshirt = NativeUI.CreateItem('T-shirt', '')
			LSPDPedPresetsSVPDTshirt:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDLongSleeveShirt = NativeUI.CreateItem('Long Sleeve Shirt', '')
			LSPDPedPresetsSVPDLongSleeveShirt:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDPolo = NativeUI.CreateItem('Polo', '')
			LSPDPedPresetsSVPDPolo:SetLeftBadge(BadgeStyle.Clothes)
			LSPDPedPresetsSVPDWindBreaker = NativeUI.CreateItem('Wind Breaker', '')
			LSPDPedPresetsSVPDWindBreaker:SetRightBadge(BadgeStyle.Style)
			LSPDPedPresetsSVPDRainCoat = NativeUI.CreateItem('Rain Coat', '')
			LSPDPedPresetsSVPDRainCoat:SetLeftBadge(BadgeStyle.Clothes)

			EUPPedPresetsLSPDsvpd:AddItem(LSPDPedPresetsSVPDClassA)
			EUPPedPresetsLSPDsvpd:AddItem(LSPDPedPresetsSVPDClassB)
			EUPPedPresetsLSPDsvpd:AddItem(LSPDPedPresetsSVPDClassC)
			EUPPedPresetsLSPDsvpd:AddItem(LSPDPedPresetsSVPDRainCoat)
			EUPPedPresetsLSPDsvpdSupervisor:AddItem(LSPDPedPresetsSVPDTshirt)
			EUPPedPresetsLSPDsvpdSupervisor:AddItem(LSPDPedPresetsSVPDLongSleeveShirt)
			EUPPedPresetsLSPDsvpdSupervisor:AddItem(LSPDPedPresetsSVPDPolo)
			EUPPedPresetsLSPDsvpdSupervisor:AddItem(LSPDPedPresetsSVPDWindBreaker)

			LSPDPedPresetsSVPDClassA.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 3, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 200, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDClassB.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 3, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 102, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDClassC.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 19, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 3, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 101, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDTshirt.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 19, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 129, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 108, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDLongSleeveShirt.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 152, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 129, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 92, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDPolo.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 41, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 129, 2, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 2, 3, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDRainCoat.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 20, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 25, 3, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 31, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 7, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 81, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

			LSPDPedPresetsSVPDWindBreaker.Activated = function(ParentMenu, SelectedItem)
				SetPedComponentVariation(GetPlayerPed(-1), 3, 152, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 4, 129, 1, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 5, 73, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 7, 1, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 10, 45, 0, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 11, 3, 11, 0)
				SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
				SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
			end

		local EUPPedPresetsBCSO = _MenuPool:AddSubMenu(EUPPedPresets, 'Blaine County Sheriff Office', '', true)
		EUPPedPresetsBCSO:SetMenuWidthOffset(20)
		local EUPPedPresetsBCSOSupervisor = _MenuPool:AddSubMenu(EUPPedPresetsBCSO, 'Supervisor', '', true)
		EUPPedPresetsLSPDsvpd:SetMenuWidthOffset(20)
		
		BCSOPedPresetClassA = NativeUI.CreateItem('Class A', '')
		BCSOPedPresetClassB = NativeUI.CreateItem('Class B', '')
		BCSOPedPresetClassC = NativeUI.CreateItem('Class C', '')
		BCSOPedPresetWinterCoat = NativeUI.CreateItem('Winter Coat', '')
		BCSOPedPresetTshirt = NativeUI.CreateItem('T-Shirt', '')
		BCSOPedPresetLongSleeve = NativeUI.CreateItem('Long Sleeve Shirt', '')
		BCSOPedPresetWindbreaker = NativeUI.CreateItem('Wind Breaker', '')
		BCSOPedPresetPolo = NativeUI.CreateItem('Polo', '')

		EUPPedPresetsBCSO:AddItem(BCSOPedPresetClassA)
		EUPPedPresetsBCSO:AddItem(BCSOPedPresetClassB)
		EUPPedPresetsBCSO:AddItem(BCSOPedPresetClassC)
		EUPPedPresetsBCSO:AddItem(BCSOPedPresetWinterCoat)
		EUPPedPresetsBCSOSupervisor:AddItem(BCSOPedPresetTshirt)
		EUPPedPresetsBCSOSupervisor:AddItem(BCSOPedPresetLongSleeve)
		EUPPedPresetsBCSOSupervisor:AddItem(BCSOPedPresetWindbreaker)
		EUPPedPresetsBCSOSupervisor:AddItem(BCSOPedPresetPolo)

		BCSOPedPresetPolo.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 85, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 47, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 48, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 37, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 94, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetWindbreaker.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 85, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 47, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 33, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 3, 9, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetLongSleeve.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 85, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 47, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 48, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 37, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 165, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetTshirt.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 85, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 47, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 48, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 37, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 208, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetClassA.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 88, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 54, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 198, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetClassB.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 88, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 54, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 256, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetClassC.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 92, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 54, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 257, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		BCSOPedPresetWinterCoat.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 88, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 25, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 8, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 266, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end

		local EUPPedPresetsSAFR = _MenuPool:AddSubMenu(EUPPedPresets, 'San Andreas Fire & Rescue', '', true)
		EUPPedPresetsSAFR:SetMenuWidthOffset(20)

		SAFRPedPresetStation = NativeUI.CreateItem('Station Wear', '')
		SAFRPedPresetStation:SetLeftBadge(BadgeStyle.Clothes)
		SAFRPedPresetTurnout1 = NativeUI.CreateItem('Turnout Gear (SCBA)', '')
		SAFRPedPresetTurnout1:SetLeftBadge(BadgeStyle.Clothes)
		SAFRPedPresetTurnout2 = NativeUI.CreateItem('Turnout Gear', '')
		SAFRPedPresetTurnout2:SetLeftBadge(BadgeStyle.Clothes)
		SAFRPedPresetChem = NativeUI.CreateItem('Chemical Suit', '')
		SAFRPedPresetChem:SetLeftBadge(BadgeStyle.Clothes)
		SAFRPedPresetHazard = NativeUI.CreateItem('Hazard Suit', '')
		SAFRPedPresetHazard:SetLeftBadge(BadgeStyle.Clothes)
		SAFRPedPresetParam = NativeUI.CreateItem('Paramedic', '')
			
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetStation)
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetTurnout1)
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetTurnout2)
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetChem)
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetHazard)
		EUPPedPresetsSAFR:AddItem(SAFRPedPresetParam)

		SAFRPedPresetParam.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 74, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 9, 7, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 37, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 17, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 74, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
		end
		SAFRPedPresetStation.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 100, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 51, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 19, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 73, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
		end
		SAFRPedPresetTurnout1.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 88, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 100, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 68, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 28, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 122, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, 124, 0, true)
		end
		SAFRPedPresetTurnout2.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 88, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 100, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 24, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 15, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 28, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, 124, 0, true)
		end
		SAFRPedPresetHazard.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 82, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 11, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 33, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 15, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 155, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, -1, 0, true)
		end
		SAFRPedPresetChem.Activated = function(ParentMenu, SelectedItem)
			SetPedComponentVariation(GetPlayerPed(-1), 3, 82, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 4, 11, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 5, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 6, 33, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 7, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 8, 15, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 10, 0, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 11, 154, 0, 0)
			SetPedComponentVariation(GetPlayerPed(-1), 1, 0, 0, 0)
			SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
		end


	
	local EUPReset = NativeUI.CreateItem('~r~Reset Ped', 'Resets your ped to core.')
	EUPMenu:AddItem(EUPReset)
	EUPReset.Activated = function(ParentMenu, SelectedItem)
		SetPedComponentVariation(GetPlayerPed(-1), 3, 0, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 4, 0, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 5, -1, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 6, 9, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 7, -1, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 8, -1, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 9, -1, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 10, -1, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 11, 0, 0, 0)
		SetPedComponentVariation(GetPlayerPed(-1), 1, -1, 0, 0)
		SetPedPropIndex(GetPlayerPed(-1), 0, 11, 0, true)
		SetPedPropIndex(GetPlayerPed(-1), 1, 0, 0, true)
	end
					
	EUPMenu:Visible(not EUPMenu:Visible())
	_MenuPool:RefreshIndex()
end

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		
		_MenuPool:ProcessMenus()	
		_MenuPool:ControlDisablingEnabled(false)
		_MenuPool:MouseControlsEnabled(false)
	end
end)